---
apps:
   - app: 'WeatherJp'
     option:
       page_key:
         '@HOME': 2
         '@JOB': 2
       display_name: 'Tokyo'
   - app: Clock
     option:
       page_key:
         '@HOME': 4
         '@JOB': 1
   - app: 'Calendar'
     option:
       page_key:
         '@JOB': 0
       command: ["google-chrome", '--profile-directory=Profile 1', 'https://calendar.google.com/calendar/u/0/r?hl=ja&tab=wc']
   - app: CommunicateDeck
     option:
       page_key:
         '@HOME': 3
       to_deck: '15key-dummy'
       to_deck_config:
         '@HOME':
            4:
             - "label": "1"
               "image": "./src/Assets/cat.png"
             - "label": "2"
               "image": "./src/Assets/world.png"
         '@GAME':
            10:
             - "label": "01"
               "image": "./src/Assets/cat.png"
             - "label": "02"
               "image": "./src/Assets/world.png"
            11:
             - "label": "01"
               "image": "./src/Assets/sad.png"
             - "label": "02"
               "image": "./src/Assets/normal.png"
             - "label": "03"
               "image": "./src/Assets/cat.png"
"games":
  RandomNumber: 0

page_config:
  "@HOME":
     keys:
       0:
         "change_page": "@PRIVATE"
         "label": "Private"
         "image": "./src/Assets/cat.png"
       1:
         "change_page": "@GAME"
         "label": "Game"
         "image": "./src/Assets/game.png"
       -1:
         "image": "./src/Assets/exit.png"
         "label": "Exit"
         "exit": 1
  "@PRIVATE":
     keys:
       0:
         "command": ["google-chrome", "--profile-directory=Default"]
         "image": "./src/Assets/chrome.png"
         "label": "Chrome"
       -2:
         "label": "Config"
         "image": "./src/Assets/settings.png"
         "change_page": "@CONFIG"
       -1:
         "change_page": "@HOME"
         "image": "./src/Assets/home.png"
  "@JOB":
     keys:
       -1:
         "change_page": "@HOME"
         "image": "./src/Assets/home.png"
  "@GAME":
     keys:
       -1:
         "change_page": "@HOME"
         "image": "./src/Assets/home.png"
  "@CONFIG":
     keys:
       0:
         "label": "Sound"
         "command": ["gnome-control-center", "sound"]
         "image": "./src/Assets/sound.png"
       1:
         "label": "Audio"
         "command": ["pavucontrol", "--tab=4"]
         "image": "./src/Assets/audio.png"
       2:
         "label": "Display"
         "command": ["gnome-control-center", "display"]
         "image": "./src/Assets/display.png"
       -1:
         "change_page": "@previous"
         "image": "./src/Assets/back.png"
         "label": "Back"
