---
apps:
   - app: 'WeatherJp'
     option:
       page_key:
         '@HOME': 2
       display_name: 'Tokyo'
   - app: WebServer
     option:
       port: 3000
   - app: Clock
     option:
       page_key:
         '@HOME': 3

page_config:
  "@HOME":
     keys:
       0:
         "change_page": "@PRIVATE"
         "label": "Private"
         "image": "./src/Assets/cat.png"
       1:
         "change_page": "@GAME"
         "label": "Game"
         "image": "./src/Assets/game.png"
  "@PRIVATE":
     keys:
       0:
         "command": ["google-chrome", "--profile-directory=Default"]
         "image": "./src/Assets/chrome.png"
         "label": "Chrome"
       -1:
         "change_page": "@HOME"
         "image": "./src/Assets/home.png"
  "@GAME":
     keys:
       0:
         "command": ["google-chrome", "--profile-directory=Default"]
         "image": "./src/Assets/chrome.png"
         "label": "Chrome"
       -1:
         "change_page": "@HOME"
         "image": "./src/Assets/home.png"
