---
apps:
   - app: Clock
     option:
       page_key:
         '@HOME': 5
         '@JOB': 12
   - app: StopWatch
     option:
       page_key:
         '@HOME': 6
   - app: Calendar
     option:
       page_key:
         '@HOME': 7
   - app: 'WeatherJp'
     option:
       page_key:
         '@HOME': 8
       display_name: 'Tokyo'
   - app: 'WeatherJp'
     option:
       page_key:
         '@HOME': 9
       division: '大阪府'
       area: '大阪府'
       area_temp: '大阪'
       display_name: 'Osaka'
   - app: 'WindowCheckLinux'
     option:
       window_title_regexps:
         - ['^Meet.+Google Chrome$', 'Meet - Google Chrome']
         - ['^(Slack \|.+?\|).+$', '\g<1>']
#   - app: 'Alert'
#     option:
#       check_interval: 180
#       key_config:
#         7:
#           command: ["google-chrome", '--profile-directory=Profile 1', 'https://example.com/nagios/cgi-bin/status.cgi?host=all&servicestatustypes=16&hoststatustypes=15']
#           image: "./src/mydeck/Assets/cat.png"
#           change_page: '@previous'
games:
  - game: RandomNumber
  - game: Memory
  - game: TicTackToe
  - game: WhacAMole
page_config:
  "@HOME":
    keys:
      0:
        "change_page": "@PRIVATE"
        "label": "Private"
        "image": "./src/mydeck/Assets/cat.png"
      1:
        "change_page": "@GAME"
        "label": "Game"
        "image": "./src/mydeck/Assets/game.png"
      13:
        "label": "Config"
        "image": "./src/mydeck/Assets/settings.png"
        "change_page": "@CONFIG"
      14:
        "image": "./src/mydeck/Assets/exit.png"
        "label": "Exit"
        "exit": 1
  "@PRIVATE":
    keys:
      0:
        "command": ["google-chrome", "--profile-directory=Default"]
        "image": "./src/mydeck/Assets/chrome.png"
        "label": "Chrome"
      13:
        "label": "Config"
        "image": "./src/mydeck/Assets/settings.png"
        "change_page": "@CONFIG"
      14:
        "change_page": "@HOME"
        "image": "./src/mydeck/Assets/home.png"
  "@CONFIG":
    keys:
      0:
        "label": "Audio"
        "command": ["pavucontrol", "--tab=4"]
        "image": "./src/mydeck/Assets/audio.png"
      1:
        "label": "Sound"
        "command": ["gnome-control-center", "sound"]
        "image": "./src/mydeck/Assets/sound.png"
      2:
        "label": "Display"
        "command": ["gnome-control-center", "display"]
        "image": "./src/mydeck/Assets/display.png"
      14:
        "change_page": "@previous"
        "image": "./src/mydeck/Assets/back.png"
        "label": "Back"
  "Meet - Google Chrome":
    keys:
      0:
        "command": ["xdotool", "key", "ctrl+d"]
        "image": "./src/mydeck/Assets/mute.png"
        "label": "mute"
      1:
        "command": ["xdotool", "key", "ctrl+e"]
        "image": "./src/mydeck/Assets/video.png"
        "label": "camera"
      10:
        "label": "Audio"
        "command": ["pavucontrol", "--tab=4"]
        "image": "./src/mydeck/Assets/audio.png"
      11:
        "label": "Sound"
        "command": ["gnome-control-center", "sound"]
        "image": "./src/mydeck/Assets/sound.png"
      14:
        "change_page": "@JOB"
        "label": "Back"
        "image": "./src/mydeck/Assets/back.png"
  "Zoom Meeting":
    keys:
      0:
        "command": ["xdotool", "key", "alt+a"]
        "image": "./src/mydeck/Assets/mute.png"
        "label": "mute"
      1:
        "command": ["xdotool", "key", "alt+v"]
        "image": "./src/mydeck/Assets/video.png"
        "label": "camera"
      10:
        "label": "Audio"
        "command": ["pavucontrol", "--tab=4"]
        "image": "./src/mydeck/Assets/audio.png"
      11:
        "label": "Sound"
        "command": ["gnome-control-center", "sound"]
        "image": "./src/mydeck/Assets/sound.png"
      14:
        "change_page": "@JOB"
        "label": "Back"
        "image": "./src/mydeck/Assets/back.png"
  "@GAME":
    keys:
      14:
        "change_page": "@HOME"
        "image": "./src/mydeck/Assets/home.png"
